### ISSUE TITLE
rdp.terminal.server.msi wants to install to an invalid pathname

### ISSUE THREAD

**Issue by dsampson01** [ilianapro/zabbix_RDP_Template#1]
When attempting to install rdp.terminal.server.msi, it aborts and complains of a pathname of `\\<server>\home\<admin name>\\WindowsPowerShell\modules\PSTerminalServices`

Please note the double backslashes prior to the WindowsPowerShell subfolder.

How can I work around this one?

**Comment by dsampson01** [comment]
I ended up using the following:
`
msiexec /i c:\apps\zabbix\rdp.terminal.server.msi APPDIR=\\<server>\home\<admin name>\WindowsPowerShell\modules\PSTerminalServices
`
and was able to install correctly.

**Comment by iSmartyPRO** [comment]
Solved by @dsampson01
